-- DEPRECATED — use migrations instead.
-- Replaced by:
--   supabase/migrations/20260212000002_leaderboard_public_read.sql (initial public read)
--   supabase/migrations/20260326000000_rls_leaderboard_only_public_reads.sql (tighten to leaderboard-only + group peers)
--
-- Do not paste this file into Supabase; run `supabase db push` or apply migrations in order.
